version: "3"
services:
  employee-jdbc:
    image: anjidockerid/springboot_docker:1.0
    container_name: my_emp_app
    ports:
      - "7777:8080"
    networks:
      - employee-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    container_name:my_sql_db
    networks:
      - employee-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb 
    ports:  
      - "9999:3306"
    volumes:
      - my-db: /var/lib/mysql    
networks:
  employee-mysql:
volumes:
  my-db:  